server:
  port: 9001

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: new-customer-consumer-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: br.com.alura.telefonica.kafka.boost.newcustomerconsumerservice.framework.helper.deserializer.CustomerDeserializer

topic:
  customer: NEW_CUSTOMER